# Generated by Django 4.0.6 on 2022-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
