# Generated by Django 4.0.6 on 2022-07-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_transaction_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(default='success', on_delete=django.db.models.deletion.CASCADE, to='cart.transaction'),
        ),
    ]
